Some more CMake generation fixes
bkaradzic/GENie pull request #515
Opened 2020-10-27 00:46 UTC by julianxhokaxhiu

- Bring minimum version back to 3.10
- Fix minor issues when building with CMake on Windows
- Fix various CMake syntax issues

2020-10-27 01:02 UTC, bkaradzic requested changes

2020-10-27 01:02 UTC, bkaradzic commented on src/actions/cmake/cmake_project.lua
> +        if os.is("windows") then
OS Windows means GENie is running on Windows, not that you're targeting Windows.

2020-10-27 01:02 UTC, bkaradzic commented on src/actions/cmake/cmake_project.lua
> +        if os.is("windows") then
I've seen this on multiple places...

2020-10-27 01:07 UTC, bkaradzic commented on src/actions/cmake/cmake_project.lua
> +            msvc_c_flags = msvc_c_flags:gsub("-Wextra ", "")
Extra warnings is coming from `ExtraWarnings`. You might want to find CMake corresponding cross-compiler option. I would be surprised if CMake didn't have something like this already.

2020-10-27 01:10 UTC, bkaradzic commented on src/actions/cmake/cmake_project.lua
> +            msvc_c_flags = msvc_c_flags:gsub("-Wextra ", "")
https://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake

2020-10-27 01:13 UTC, bkaradzic commented on src/actions/cmake/cmake_project.lua
> +            msvc_c_flags = msvc_c_flags:gsub("-Wextra ", "")
You could do (replace `/W[0-4]` with `/WX`, and `-Wextra`):

```
if cfg.flags.ExtraWarnings then
_p("if(MSVC)")
_p("  if(CMAKE_CXX_FLAGS MATCHES "/W[0-4]")")
_p("    string(REGEX REPLACE "/W[0-4]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")")
_p("  else()")
_p("    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4")")
_p("  endif()")
_p("elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)")
_p("  # Update if necessary")
_p("  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-long-long -pedantic")")
_p("endif()")
end
```

2020-10-27 13:27 UTC, julianxhokaxhiu commented on src/actions/cmake/cmake_project.lua
> +        if os.is("windows") then
Let me know the best way to fix this, if you're willing to merge this PR

2021-05-28 02:21 UTC, Sebanisu commented on src/actions/cmake/cmake_project.lua
> +            msvc_c_flags = msvc_c_flags:gsub("-Wextra ", "")
Might be better to use [target_compiler_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html) instead of setting CMAKE_CXX_FLAGS.
I believe it's a better practice to target things than setting global values.
[modern-cmake.pdf](https://cliutils.gitlab.io/modern-cmake/modern-cmake.pdf) is a good resource for modern cmake best practices.
[cpp_starter_project](https://github.com/lefticus/cpp_starter_project) has a modern cmakelists I've been using for reference as I learn how to use it better. Also it's a got a good list of many warnings you can enable in Clang GCC and MSVC.

2021-07-31 23:17 UTC, julianxhokaxhiu commented on src/actions/cmake/cmake_project.lua
> +            msvc_c_flags = msvc_c_flags:gsub("-Wextra ", "")
Sorry, i lost this comment somehow, I'll try to get merged your suggestion, thank you

2022-08-29 12:56 UTC, closed without merging